# .github/workflows/tests.yml
name: Tests

on:
  push:
    branches:
      - '!main'
      - '!release-**'
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: "Install Nix ❄"
        uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
        with:
            extra_nix_config: |
              experimental-features = nix-command flakes

      - name: "Run clippy"
        run: nix develop -c cargo clippy

      - name: "Check formatting"
        run: nix develop -c cargo fmt --check

  test:
    needs: lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: "Install Nix ❄"
        uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
        with:
            extra_nix_config: |
              experimental-features = nix-command flakes

      - name: Create SQLite Database
        run: |
          touch database/database.sqlite

      - name: Copy Environment File
        run: cp .env.ci .env

      - name: Run Tests
        run: nix develop -c cargo test
